### ISSUE TITLE
Agent's Wall not decremented and dumb

### ISSUE THREAD

**Issue by ddnguyen1494** [ddnguyen1494/quoridor-ai#1]
Bug:
- Agent wall not decremented after placing wall (this can wait till the Action is refactored)
- Agent placing random walls instead of ones that actually matters, i.e block the opponent's path. Either bug in Evaluate function or it's not good enough.

**Comment by ddnguyen1494** [comment]
The undoing vertical and horizontal wall are having a lot of issues:
- Number of walls are not being decremented correctly
- Crash after AI places 10 walls
- AStarSearch is affected because walls are not being removed.

**Comment by FullertonDavidBrown** [comment]
What file is this located in? I may be able to look tomorrow.

**Comment by FullertonDavidBrown** [comment]
I do not notice this issue any more. The CPU also seems to place walls intelligently. I am closing the isue now.
